# Generated by Django 2.1.2 on 2018-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceType',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Surface Type',
                'verbose_name_plural': 'Surface Types',
                'ordering': ['name'],
            },
        ),
    ]
