# Generated by Django 2.1.2 on 2018-10-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacetype',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='airport.Airport'),
        ),
    ]
