# Generated by Django 2.1.2 on 2018-10-19 18:43

from django.db import migrations


def set_surface_default_airport(apps, schema_editor):
    Airport = apps.get_model('airport', 'Airport')
    SurfaceType = apps.get_model('airport', 'SurfaceType')
    airport = Airport.objects.first()
    if airport is None:
        airport = Airport.objects.create(
            name="Dummy Airport",
            code="AAAA",
            website="notawebsite"
        )
    # Assign all existing surfaces to a dummy Airport to make the field mandatory
    for surface_type in SurfaceType.objects.all():
        surface_type.airport = airport
        surface_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_surfacetype_airport'),
    ]

    operations = [
        migrations.RunPython(
            set_surface_default_airport, migrations.RunPython.noop)
    ]
