# Generated by Django 2.1.2 on 2018-10-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_auto_20181019_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacetype',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='airport.Airport'),
        ),
    ]
