# Generated by Django 2.1.2 on 2018-10-22 14:40

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_auto_20181019_1900'),
    ]

    operations = [
        CreateExtension('postgis')
    ]
