# Generated by Django 2.1.2 on 2018-10-22 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_auto_20181022_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('surface_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='airport.SurfaceType')),
            ],
            options={
                'verbose_name_plural': 'Surface Shapes',
            },
        ),
    ]
