# Generated by Django 2.1.2 on 2018-10-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_surfaceshape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacetype',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_types', to='airport.Airport'),
        ),
    ]
