# Generated by Django 2.1.3 on 2018-12-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_auto_20181217_1349'),
        ('airport', '0009_auto_20181025_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='safety_self_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_airport', to='inspections.InspectionParent'),
        ),
    ]
