# Generated by Django 2.1.3 on 2019-01-08 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_airport_safety_self_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
