# Generated by Django 2.1.3 on 2019-02-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0013_auto_20190122_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='asset_types/')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='airport.Airport')),
            ],
        ),
    ]
