# Generated by Django 2.1.3 on 2019-02-11 18:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0014_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='airport.Airport')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='airport.SurfaceShape')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='airport.AssetType')),
            ],
        ),
    ]
