# Generated by Django 2.1.3 on 2019-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0017_auto_20190215_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
