# Generated by Django 2.1.3 on 2019-02-18 18:22

from django.db import migrations, models


def create_default_categores(apps, schema_editor):
    AssetCategory = apps.get_model('airport', 'AssetCategory')

    a1 = AssetCategory(name="Signs")
    a1.save()

    a2 = AssetCategory(name="Lights")
    a2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0018_asset_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.RunPython(
            create_default_categores,
            migrations.RunPython.noop)
    ]
