# Generated by Django 2.1.3 on 2019-02-19 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import forms.models


def create_default_schemas(apps, schema_editor):
    AssetForm = apps.get_model('airport', 'AssetForm')
    AssetCategory = apps.get_model('airport', 'AssetCategory')
    AssetVersion = apps.get_model('airport', 'AssetVersion')
    Airport = apps.get_model('airport', 'Airport')

    for airport in Airport.objects.all():
        af = AssetForm.objects.create(
            title="{} Signs form".format(airport.name),
            airport=airport,
            category=AssetCategory.objects.get(name="Signs")
        )
        AssetVersion.objects.create(form=af, status=1)

        af = AssetForm.objects.create(
            title="{} Lights form".format(airport.name),
            airport=airport,
            category=AssetCategory.objects.get(name="Lights")
        )
        AssetVersion.objects.create(form=af, status=1)


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0020_assettype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_forms', to='airport.Airport')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='airport.AssetCategory')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='airport.AssetForm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='version_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='airport.AssetVersion'),
        ),
        migrations.RunPython(
            create_default_schemas,
            migrations.RunPython.noop)
    ]
