# Generated by Django 2.1.3 on 2019-02-19 17:22

from django.db import migrations, models
import django.db.models.deletion


def create_default_schemas(apps, schema_editor):
    AssetForm = apps.get_model('airport', 'AssetForm')
    Asset = apps.get_model('airport', 'Asset')

    for asset in Asset.objects.all():
        asset.version_schema = AssetForm.objects.get(
            airport=asset.airport,
            category=asset.asset_type.category).versions.first()
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0021_auto_20190219_1717'),
    ]

    operations = [
        migrations.RunPython(
            create_default_schemas,
            migrations.RunPython.noop),

        migrations.AlterField(
            model_name='asset',
            name='version_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='airport.AssetVersion'),
        ),
    ]
