# Generated by Django 2.1.3 on 2019-02-27 17:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def fill_types(apps, schema_editor):
    Airport = apps.get_model('airport', 'Airport')

    config = {}
    for airport in Airport.objects.all():
        self_inspection = airport.safety_self_inspection
        if self_inspection:
            schema = self_inspection.versions.get(status=1).schema
            section = schema['sections'][1]
            fields = schema['fields']
            for f in section['fields']:
                fi = next((x for x in fields if x['id'] == f), None)
                config[f] = {}
                for ch in list(map(lambda x: x['key'], fi['checklist'])):
                    config[f][ch] = ''
        airport.types_for_self_inspection = config
        airport.save()


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0022_auto_20190219_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='types_for_self_inspection',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(
            fill_types,
            migrations.RunPython.noop)
    ]
