# Generated by Django 2.1.3 on 2019-02-28 14:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0023_airport_types_for_self_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='types_for_self_inspection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
