# Generated by Django 2.1.3 on 2019-03-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0024_auto_20190228_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airport.Asset')),
            ],
        ),
    ]
