# Generated by Django 2.1.3 on 2019-06-28 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0025_assetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(help_text='ICAO Code', max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
