# Generated by Django 2.1.3 on 2019-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0026_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
