# Generated by Django 2.1.3 on 2019-06-28 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0026_auto_20190628_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country_code',
            field=models.CharField(default='USA', max_length=3, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
