# Generated by Django 2.1.3 on 2019-07-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0027_airport_default_language'),
        ('airport', '0027_airport_country_code'),
    ]

    operations = [
    ]
