# Generated by Django 2.1.3 on 2019-07-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0029_auto_20190729_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportpermission',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airport.Airport'),
        ),
        migrations.RemoveField(
            model_name='airportpermission',
            name='modules',
        ),
        migrations.AddField(
            model_name='airportpermission',
            name='modules',
            field=models.ManyToManyField(to='airport.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
