# Generated by Django 2.1.3 on 2019-08-13 07:44

from django.db import migrations


def create_modules(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0030_auto_20190729_1525'),
    ]

    operations = [
        migrations.RunPython(create_modules),
    ]
