# Generated by Django 2.1.3 on 2019-08-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0031_auto_20190813_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=5)),
                ('airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_feature', to='airport.Airport')),
                ('modules', models.ManyToManyField(to='airport.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='airportpermission',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='airportpermission',
            name='modules',
        ),
        migrations.DeleteModel(
            name='AirportPermission',
        ),
    ]
