# Generated by Django 2.1.3 on 2019-08-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0032_auto_20190814_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModuleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_inspection_parents', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='airportfeature',
            name='modules',
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='airportmoduleconfig',
            name='airport_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.AirportFeature'),
        ),
        migrations.AddField(
            model_name='airportmoduleconfig',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Module'),
        ),
    ]
