# Generated by Django 2.1.3 on 2019-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0033_auto_20190814_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportfeature',
            name='modules',
            field=models.ManyToManyField(through='airport.AirportModuleConfig', to='airport.Module'),
        ),
    ]
