# Generated by Django 2.1.3 on 2019-08-14 05:20

from django.db import migrations

def create_modules(apps, schema_editor):
    Module = apps.get_model("airport", "Module")
    Module.objects.bulk_create([
        Module(name="Assets", code="assets"),
        Module(name="Inspections", code="inspections"),
        Module(name="Tasks", code="tasks"),
        Module(name="Work Orders", code="work_orders")
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0034_airportfeature_modules'),
    ]

    operations = [
        migrations.RunPython(create_modules),
    ]
