# Generated by Django 2.1.3 on 2019-08-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0035_auto_20190814_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportmoduleconfig',
            old_name='max_inspection_parents',
            new_name='max_count',
        ),
    ]
