# Generated by Django 2.1.3 on 2019-08-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0036_auto_20190814_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportfeature',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_feature', to='airport.Airport', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='airportmoduleconfig',
            unique_together={('airport_feature', 'module')},
        ),
    ]
