# Generated by Django 2.1.3 on 2019-08-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0037_auto_20190820_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportfeature',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_feature', to='airport.Airport', unique=True),
        ),
    ]
