# Generated by Django 2.1.3 on 2019-09-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0038_auto_20190824_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportfeature',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='airportfeature',
            name='modules',
        ),
        migrations.AlterUniqueTogether(
            name='airportmoduleconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='airportmoduleconfig',
            name='airport_feature',
        ),
        migrations.RemoveField(
            model_name='airportmoduleconfig',
            name='module',
        ),
        migrations.DeleteModel(
            name='AirportFeature',
        ),
        migrations.DeleteModel(
            name='AirportModuleConfig',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
