# Generated by Django 2.1.3 on 2018-11-05 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0009_auto_20181025_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AerosimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='airport.Airport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aerosimple_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
