# Generated by Django 2.1.3 on 2018-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosimpleuser',
            name='fullname',
            field=models.CharField(default='fullname', max_length=100),
            preserve_default=False,
        ),
    ]
