# Generated by Django 2.1.3 on 2019-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0003_auto_20190117_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(related_name='config', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
