# Generated by Django 2.1.3 on 2019-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190118_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosimpleuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='aerosimpleuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=16, null=True),
        ),
    ]
