# Generated by Django 2.1.3 on 2019-06-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190118_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosimpleuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
