# Generated by Django 2.1.3 on 2019-07-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190624_1005'),
        ('users', '0006_aerosimpleuser_language'),
    ]

    operations = [
    ]
