# Generated by Django 2.1.3 on 2019-07-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20190701_1141'),
        ('users', '0007_auto_20190712_0906'),
    ]

    operations = [
    ]
