# Generated by Django 2.1.3 on 2019-08-23 18:45

from django.db import migrations
from backend.init_roles import init_groups


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20190715_1152'),
        ('operations_log', '0004_logtype_system_generated'),
    ]

    operations = [
        migrations.RunPython(
            init_groups, migrations.RunPython.noop)
    ]
