# Generated by Django 2.1.3 on 2019-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190826_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
