# Generated by Django 2.1.3 on 2019-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0038_auto_20190824_0654'),
        ('users', '0009_auto_20190823_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosimpleuser',
            name='authorized_airports',
            field=models.ManyToManyField(to='airport.Airport'),
        ),
    ]
