# Generated by Django 2.1.3 on 2019-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_role_system_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerosimpleuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
