# Generated by Django 2.1.3 on 2019-08-28 14:34

from django.db import migrations


def set_authorized_airports(apps, schema_editor):
    AerosimpleUser = apps.get_model('users', 'AerosimpleUser')
    users = AerosimpleUser.objects.all()
    for user in users:
        user.authorized_airports.add(user.airport)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_aerosimpleuser_authorized_airports'),
    ]

    operations = [
        migrations.RunPython(
            set_authorized_airports, migrations.RunPython.noop)
    ]
