# Generated by Django 2.1.3 on 2019-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190828_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerosimpleuser',
            name='authorized_airports',
            field=models.ManyToManyField(blank=True, null=True, to='airport.Airport'),
        ),
    ]
