# Generated by Django 2.1.3 on 2019-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191204_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosimpleuser',
            name='access_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
