# Generated by Django 2.1.3 on 2019-07-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Secttion', 'verbose_name_plural': 'Sections'},
        ),
    ]
