# Generated by Django 2.1.3 on 2019-01-03 20:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0010_airport_safety_self_inspection'),
        ('users', '0002_aerosimpleuser_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('completed_on', models.DateTimeField()),
                ('work_description', models.TextField()),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_completed', to='users.AerosimpleUser')),
            ],
            options={
                'verbose_name': 'Maintenance Step (Work Orders)',
                'verbose_name_plural': 'Maintenance Steps (Work Orders)',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_orders/')),
                ('maintenance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='work_orders.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='work_orders.MaintenanceForm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('completed_on', models.DateTimeField()),
                ('review_report', models.TextField()),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_completed', to='users.AerosimpleUser')),
            ],
            options={
                'verbose_name': 'Operations Step (Work Orders)',
                'verbose_name_plural': 'Operation Steps (Work Orders)',
            },
        ),
        migrations.CreateModel(
            name='OperationsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_orders/')),
                ('operations_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='work_orders.Operations')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='work_orders.OperationsForm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('priority', models.IntegerField(choices=[(2, 'High'), (1, 'Medium'), (0, 'Low')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Pending Maintenance Review'), (2, 'Pending Operations Review'), (3, 'Completed')], default=1)),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('report_date', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('problem_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_schema', to='airport.Airport')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_orders/')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='work_orders.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='work_orders.WorkOrderForm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='work_orders.WorkOrderSchema'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_work_orders', to='users.AerosimpleUser'),
        ),
        migrations.AddField(
            model_name='operationsform',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operations_form', to='work_orders.WorkOrderForm'),
        ),
        migrations.AddField(
            model_name='operations',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='work_orders.OperationsSchema'),
        ),
        migrations.AddField(
            model_name='operations',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_answer', to='work_orders.WorkOrder'),
        ),
        migrations.AddField(
            model_name='maintenanceform',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_form', to='work_orders.WorkOrderForm'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='work_orders.MaintenanceSchema'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_answer', to='work_orders.WorkOrder'),
        ),
    ]
