# Generated by Django 2.1.3 on 2019-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_auto_20190111_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderform',
            options={'permissions': (('can_modify_workorder_schema', 'Can modify Work Order Schema'),)},
        ),
    ]
