# Generated by Django 2.1.3 on 2019-02-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190118_2009'),
        ('work_orders', '0005_auto_20190131_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance Answer', 'verbose_name_plural': 'Maintenance Answers'},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name': 'Operations Answer', 'verbose_name_plural': 'Operations Answers'},
        ),
        migrations.AddField(
            model_name='operationsform',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_assigned_role', to='users.Role'),
        ),
        migrations.AddField(
            model_name='operationsform',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='operations_assigned_users', to='users.AerosimpleUser'),
        ),
        migrations.AlterField(
            model_name='maintenanceform',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_role', to='users.Role'),
        ),
        migrations.AlterField(
            model_name='maintenanceform',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='maintenance_assigned_users', to='users.AerosimpleUser'),
        ),
    ]
