# Generated by Django 2.1.3 on 2019-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_workorder_notams'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='zoom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
