# Generated by Django 2.1.3 on 2019-04-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20190118_2009'),
        ('schedule', '0011_event_calendar_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('attached', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.Role')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.AerosimpleUser')),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_occurrences', to='schedule.Occurrence')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_occurrences', to='tasks.Task')),
            ],
        ),
    ]
