# Generated by Django 2.1.3 on 2019-04-04 14:42

from django.db import migrations


def create_default_rules(apps, schema_editor):
    Rule = apps.get_model('schedule', 'Rule')

    daily = Rule.objects.create(
        name="Daily", frequency="DAILY", description="Repeats daily")
    daily.save()

    weekday = Rule.objects.create(
        name="Weekday", frequency="DAILY",
        description="Repeats from Monday to Friday",
        params="BYWEEKDAY=MO,TU,WE,TH,FR;INTERVAL=1")
    weekday.save()

    weekly = Rule.objects.create(
        name="Weekly", frequency="WEEKLY", description="Repeats weekly")
    weekly.save()

    monthly = Rule.objects.create(
        name="Monthly", frequency="MONTHLY", description="Repeats monthly")
    monthly.save()

    yearly = Rule.objects.create(
        name="Yearly", frequency="YEARLY", description="Repeats yearly")
    yearly.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_rules,
            migrations.RunPython.noop)
    ]
