# Generated by Django 2.1.3 on 2019-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0040_auto_20191001_1518'),
        ('tasks', '0002_auto_20190404_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='airport.Airport'),
        ),
    ]
