# Generated by Django 2.1.3 on 2019-05-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_log', '0002_auto_20190503_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='subcategory',
            new_name='subtype',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='category',
            new_name='type',
        ),
    ]
