# Generated by Django 2.1.3 on 2019-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_log', '0003_auto_20190510_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtype',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
