# Generated by Django 2.1.3 on 2019-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_log', '0004_logtype_system_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logs', to='users.AerosimpleUser'),
        ),
        migrations.AlterField(
            model_name='log',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logs', to='operations_log.LogSubType'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logs', to='operations_log.LogType'),
        ),
    ]
