# Generated by Django 2.1.3 on 2019-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_log', '0005_auto_20191022_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='subtype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
