# Generated by Django 2.1.3 on 2018-12-13 18:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_aerosimpleuser_fullname'),
        ('airport', '0009_auto_20181025_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('additionalInfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('inspection_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('weather_conditions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('inspection_type', models.CharField(max_length=100)),
                ('issues', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_created', to='users.AerosimpleUser')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_answers', to='users.AerosimpleUser')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_answer', to='inspections.Inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('additionalInfo', models.TextField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_parents', to='airport.Airport')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_parents', to='users.AerosimpleUser')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inspections.InspectionParent'),
        ),
    ]
