# Generated by Django 2.1.3 on 2018-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionanswer',
            name='status',
            field=models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='remark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='remarks/'),
        ),
    ]
