# Generated by Django 2.1.3 on 2019-04-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190404_1442'),
        ('inspections', '0003_auto_20181217_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionparent',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection', to='tasks.Task'),
        ),
    ]
