# Generated by Django 2.1.3 on 2019-05-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_log', '0001_initial'),
        ('inspections', '0004_inspectionparent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionparent',
            name='activity_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_parents', to='operations_log.LogSubType'),
        ),
        migrations.AddField(
            model_name='inspectionparent',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_parents', to='operations_log.LogType'),
        ),
    ]
