# Generated by Django 2.1.3 on 2019-05-06 19:21

from django.db import migrations


def create_default_log_types_for_inspections(apps, schema_editor):
    Airport = apps.get_model('airport', 'Airport')
    InspectionParent = apps.get_model('inspections', 'InspectionParent')
    LogType = apps.get_model('operations_log', 'LogType')
    LogSubType = apps.get_model('operations_log', 'LogSubType')

    for airport in Airport.objects.all():
        inspection_type = LogType.objects.create(
            name="Inspections",
            airport=airport
        )
        inspection_type.system_generated = True
        inspection_type.save()

        for inspection in InspectionParent.objects.filter(airport=airport):
            inspection_subtype = LogSubType.objects.create(
                name=inspection.title,
                activity_type=inspection_type
            )
            inspection.activity_type = inspection_type
            inspection.activity_subtype = inspection_subtype
            inspection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20190507_1759'),
        ('operations_log', '0004_logtype_system_generated'),
    ]

    operations = [
        migrations.RunPython(
            create_default_log_types_for_inspections,
            migrations.RunPython.noop),
    ]
