# Generated by Django 2.1.3 on 2019-05-31 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_auto_20190510_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=forms.models.version_default)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Expired')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('additionalInfo', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inspections.InspectionTemplateForm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspectionparent',
            name='airport_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='inspectionparent',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.InspectionTemplateVersion'),
        ),
    ]
