# Generated by Django 2.1.3 on 2019-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20190531_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplateform',
            name='repo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
