# Generated by Django 2.1.3 on 2019-05-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0025_assetimage'),
        ('inspections', '0010_inspectiontemplateform_repo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTemplatesRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_version', models.IntegerField(default=1)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_relation', to='airport.Airport')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_relations', to='inspections.InspectionTemplateForm')),
            ],
        ),
    ]
