# Generated by Django 2.1.3 on 2019-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_airporttemplatesrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionparent',
            name='activity_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_parents', to='operations_log.LogSubType'),
        ),
        migrations.AlterField(
            model_name='inspectionparent',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_parents', to='operations_log.LogType'),
        ),
    ]
